spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb?characterEncoding=UTF-8&useUnicode=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  profiles:
    active: local
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true